// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsp7JphTjHl3fsKq_lQe1HR-zcdlWmieE',
    appId: '1:961493243272:web:0cb93edd0f9327a290d63d',
    messagingSenderId: '961493243272',
    projectId: 'ngo-smvm-16110',
    authDomain: 'ngo-smvm-16110.firebaseapp.com',
    storageBucket: 'ngo-smvm-16110.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcImg52usNjMNE-eO6M7JWBqNjb5Mkwlk',
    appId: '1:961493243272:android:edf767357069b8de90d63d',
    messagingSenderId: '961493243272',
    projectId: 'ngo-smvm-16110',
    storageBucket: 'ngo-smvm-16110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC68a24mcXndcR68dxkkgFB_OknvEnV5ak',
    appId: '1:961493243272:ios:051e6b46839df8c390d63d',
    messagingSenderId: '961493243272',
    projectId: 'ngo-smvm-16110',
    storageBucket: 'ngo-smvm-16110.appspot.com',
    iosBundleId: 'com.example.smvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC68a24mcXndcR68dxkkgFB_OknvEnV5ak',
    appId: '1:961493243272:ios:03ec81321f3ff24290d63d',
    messagingSenderId: '961493243272',
    projectId: 'ngo-smvm-16110',
    storageBucket: 'ngo-smvm-16110.appspot.com',
    iosBundleId: 'com.example.smvm.RunnerTests',
  );
}
